name: Node.js CI

on:
  pull_request:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: setup git config
        run: |
          git config user.name "Sadanand Pai"
          git config user.email "sadypai@gmail.com"

      - name: setup deployment
        run: |
          npm install
          npm run unit:test
          npm run build
